name: Update Version on Push

on:
  push:
    branches:
      - main
      - master

jobs:
  update-version:
    runs-on: ubuntu-latest
    # Solo ejecutar si NO es un commit de github-actions
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version.json
        run: |
          cat > public/version.json << EOF
          {
            "version": "1.0.0",
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%S.%3NZ")",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}"
          }
          EOF

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/version.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore: update version.json [skip ci]" && git push)
